config/routes.rb
DotaMarket::Application.routes.draw do


  concern :commentable do
    resources :comments
  end

  resources :users, concerns: :commentable do
    resources :messages do
      get "sent_messages", on: :collection
      get "conversation",  on: :collection
      member do 
        get 'marked_as_read'
      end
    end
   resources :user_listings
   resources :relationships, only: [:create, :update] #[:new, :create, :edit, :update, :destroy]
 end

  resources :user_listings, concerns: :commentable
 
  resources :items
  resources :sessions, only: [:create, :destroy]

  # SESSIONS ROUTES START #

  get  'auth/steam/callback' => 'sessions#create'
  post 'auth/steam/callback' => 'sessions#create'
  get  'auth/failure'         => redirect('/')
  delete 'signout'           => 'sessions#destroy'
  # match '/signout', to: 'sessions#destroy', via: :delete

  # SESSIONS ROUTES END #


  #resources :user_listings

  root to: 'static_pages#home'

  ### SHAMEFUL ROUTES BELOW ###

  get "search/new"
  get "search/create"
  get "search/show"
  match '/searched-items', to: 'search#show', via: :get
  match '/search', to: "user_listings#search", via: :get

  match "/faq", to: "static_pages#faq", via: :get
  match "/about", to: "static_pages#about", via: :get
  # match "/contact", to: "static_pages#contact"

  match '/reload', to: "user_listings#reload", via: :post

  match '/contact', to: "contact_messages#new", via: :get
  match '/signin', to: redirect('/auth/steam'), via: :get
  # match '/message_marked_as_read', to: "messages#marked_as_read"
  match '/block_user', to: "relationships#create", via: :get
  match '/unblock_user', to:  "relationships#update", via: :get
  match '/update', to: "users#update", via: :get


  ### SHAMEFUL ROUTES END ###
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :messenger_id, :recipient_id
  before_create :set_default_status
  validates_length_of :content, :minimum => 1,
                                :wrong_length => "should be more than one {{count}} character"


    belongs_to :messenger, 
               class_name: "User",
               foreign_key: "messenger_id"


    belongs_to :recipient, 
               class_name: "User",
               foreign_key: "recipient_id"

    scope :unread, ->(user) { where("status = ? AND recipient_id = ?", "unread", user) }

    def set_status_to_read
      self.status = "read"
      self.save
    end

    def self.unread_msg_count(user)
      self.unread(user).count
    end

    def set_default_status
      self.status = "unread"
    end

    def self.conversation(users)
      messenger = users[:messenger]
      recipient = users[:recipient]
      Message.where(["(messenger_id = ? AND recipient_id = ?) OR (messenger_id = ? AND recipient_id = ?)", 
                                messenger.id, recipient.id, recipient.id, messenger.id])
                                .order("created_at DESC")
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_filter :signed_in_user, only: [:create, :new, :show, :index, :destroy]
    before_filter :correct_user, only: [:index, :create, :destroy]

    def index
        @user = current_user
        @message = @user.messages.paginate(:page => params[:page]).per_page(10)
        @received_messages = @user.received_messages
    end

    def new
        @user = current_user
        @recipient = User.find(params[:recipient])
        @message = @user.messages.new
    end

    def create
        @user = current_user
        @recipient = User.find(params[:recipient_id])
        @content = params[:message][:content]
        @new_message = @user.messages.new({content: @content, recipient_id: @recipient.id, messenger_id: @user.id})
        if @new_message.save
          flash[:success] = "You message has successfully been sent"
          redirect_to user_messages_path(@user)
        else 
          flash[:alert] = "Message failed. Make sure you type a message! :D"
          redirect_to new_user_message_path(@user, {:recipient => @recipient})
        end
        
    end

    def show

        @user = current_user
        @message = Message.find(params[:id])
        @conversation = Message.where(["(messenger_id = ? AND recipient_id = ?) OR (messenger_id = ? AND recipient_id = ?)", 
                                @message.messenger_id, @message.recipient_id, @message.recipient_id, @message.messenger_id])
                                .order("created_at DESC")
    end

    def destroy
        @user = User.find(params[:user_id])
        @message = Message.find(params[:id])
        if @message.destroy
          flash[:success] = "You have successfully deleted the message"
        end
        redirect_to user_messages_path(@user)
    end

    def sent_messages
        @user = User.find(params[:user_id])
    end

    def conversation
        puts params
        @user = current_user
        @message = Message.find(params[:id])
        @recipient = User.find(@message.recipient.id)
        @conversation = Conversation.new({messenger: current_user, recipient: @recipient})
    end

    def marked_as_read
        @message = Message.find(params[:id])
        if @message.set_status_to_read
          flash[:success] = "You have successfully marked the message as read"
        end
        redirect_to user_messages_path(@message.recipient)
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
  def unread_messages(user)
    Message.unread(user).count
  end
end

app/views/layouts/messages/_message.html.erb
<div class="message-section row" data-message-id=<%= message.id %>>
    <%= link_to url_for(message.messenger) do %>
      <div class="avatar col-xs-1">
          <span>
              <img class="img-responsive" src="<%= message.messenger.avatar_medium %>">
          </span>
      </div>
    <% end %>

    <div class="comment-header group col-xs-9">
        <div class="title clearfix">
            <%= link_to url_for(message.messenger) do %>
            <span class="messenger-name"><%= message.messenger.steam_name %> posted <%= time_ago_in_words(message.created_at) %> ago...</span>
            <% end %>
            <div class="btn-group pull-right">
              <% unless current_user == message.messenger %>
                <div type="button" class="btn btn-inverse"><%= link_to new_user_message_path({recipient: message.messenger}) do %>
                      <i class="pull-right icon fa fa-reply"></i>
                  <% end %>
                </div>
              <% end %>
              
              <div type="button" class="btn btn-inverse"><%= link_to user_message_path({:id => message.id}) do %>
                <i class="pull-right icon fa fa-comments"></i>
              <% end %>
              </div>

               <div type="button" class="btn btn-inverse" data-toggle="modal" data-target="#myModal"><%= link_to url_for([@user, message]), class: "deleteButton" do %>
                    <i class="pull-right icon glyphicon glyphicon-trash"></i>
                <% end %>
               </div>
                
                <% if message.status == "unread" %>
                  <div type="button" class="mark-btn btn btn-inverse"><%= link_to marked_as_read_user_message_path(@user, message) do %>
                      <i class="pull-right icon fa fa-check-square"></i>
                  <% end %>
                  </div>
                <% end %>
            </div>
        </div>

        <div class="menu comment-description">
            <%= message.content %>
        </div>
    </div>
 </div>