config/routes.rb
DotaMarket::Application.routes.draw do


  concern :commentable do
    resources :comments
  end

  resources :users, concerns: :commentable do
    resources :messages do
      get "sent_messages", on: :collection
      get "conversation",  on: :collection
      member do 
        get 'marked_as_read'
      end
    end
   resources :user_listings
   resources :relationships, only: [:create, :update] #[:new, :create, :edit, :update, :destroy]
 end

  resources :user_listings, concerns: :commentable
 
  resources :items
  resources :sessions, only: [:create, :destroy]

  # SESSIONS ROUTES START #

  get  'auth/steam/callback' => 'sessions#create'
  post 'auth/steam/callback' => 'sessions#create'
  get  'auth/failure'         => redirect('/')
  delete 'signout'           => 'sessions#destroy'
  # match '/signout', to: 'sessions#destroy', via: :delete

  # SESSIONS ROUTES END #


  #resources :user_listings

  root to: 'static_pages#home'

  ### SHAMEFUL ROUTES BELOW ###

  get "search/new"
  get "search/create"
  get "search/show"
  match '/searched-items', to: 'search#show', via: :get
  match '/search', to: "user_listings#search", via: :get

  match "/faq", to: "static_pages#faq", via: :get
  match "/about", to: "static_pages#about", via: :get
  # match "/contact", to: "static_pages#contact"

  match '/reload', to: "user_listings#reload", via: :post

  match '/contact', to: "contact_messages#new", via: :get
  match '/signin', to: redirect('/auth/steam'), via: :get
  # match '/message_marked_as_read', to: "messages#marked_as_read"
  match '/block_user', to: "relationships#create", via: :get
  match '/unblock_user', to:  "relationships#update", via: :get
  match '/update', to: "users#update", via: :get


  ### SHAMEFUL ROUTES END ###
end

app/models/user.rb
require 'get_data'

class User < ActiveRecord::Base
  extend GetData 
  attr_accessible :steam_id, :steam_name, :profile_url, :community_visibility, 
  :profile_state, :last_logoff, :avatar, :avatar_medium, :avatar_full, 
  :primary_clanid, :time_created, :person_state, :received_messages, :other_user_id,
  :trade_url

  before_save :create_remember_token

  has_many :user_items, dependent: :destroy
  has_many :items, through: :user_items

  has_many :user_listings, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :messages, 
           foreign_key: "messenger_id",
           dependent: :destroy
  has_many :received_messages, 
           class_name: "Message",
           foreign_key: "recipient_id"

  has_many :relationships, dependent: :destroy
  has_many :other_users,  :through => :relationships,
                          :source  => :other_user

  validates :steam_id, presence: true
  validates :steam_name, presence: true
  validates :avatar, presence: true
  validates :avatar_medium, presence: true
  validates :avatar_full, presence: true

  ## validate trade_url

  def blocked_relationships(user_id, other_user_id)
    Relationship.blocked_relationships(user_id, other_user_id)
  end

  def blocked_users
    other_users.where("status = ?", "blocked")
  end

  def self.is_relationship_blocked?(user, other_user)
    Relationship.any_blocked_relationship?(user, other_user)
  end

  ## start testing here

  def has_items?
    !user_items.empty?
  end

  ## need to work on reload_player_items

  def reload_player_items
    # temporary solution
    begin 
      get_user_items
    rescue SocketError => e 
      puts "in reload_player_items"
      puts e
      puts "There was a socket error, perhaps your are not connected to the internet?"
      return 
    end
    user_items.delete_all
    create_player_items
  end

  ## need to fix rescue, can't rescue all errors

  def get_user_items
    url = "http://api.steampowered.com/IEconItems_570/GetPlayerItems/v0001?SteamID=" + steam_id + "&key=" + ENV["STEAM_WEB_API_KEY"]
    User.parsed_data(url)  # reading HTTP request using open-uri, returns a hash that is a parsed JSON object
  end

  def create_player_items
    merge_items.each do |item|
      user_items.create!(item)
    end
  end

  def merge_items
    merged_items_array = []
    items = Item.where(:defindex => defindex_ids).to_a
    player_item_hash.each do |i|
      items.each do |item|
        if i["defindex"].to_s == item.defindex
          array_with_attributes = {}
          array_with_attributes["item_id"]          = item.id
          array_with_attributes["equipped"]         = i["equipped"]
          array_with_attributes["quality"]          = i["quality"]
          array_with_attributes["rarity"]           = item.rarity
          array_with_attributes["name"]             = item.name
          array_with_attributes["defindex"]         = i["defindex"]
          array_with_attributes["image_url"]        = item.image_url
          array_with_attributes["item_description"] = item.item_description
          array_with_attributes["item_set"]         = item.item_set
          merged_items_array.push(array_with_attributes)
        end
      end
    end
    return merged_items_array
  end

  private

  def player_item_hash
    @player_item_hash ||= get_user_items["result"]["items"]
  end

  def defindex_ids
    player_item_hash.map { |item| item["defindex"].to_s }
  end

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def self.from_omniauth(auth)
    # find a user by their UID (assigned by Steam) by using ActiveRecord dynamic finder
    auth_user = self.find_by(steam_id: auth["uid"])
    ## create player in db unless they exist already
    if auth_user
      return auth_user
    else 
      self.create_from_omniauth(auth)
    end
  end

  def self.create_from_omniauth(auth)
    info = auth["extra"]["raw_info"]
    User.create! do |u| 
      u.steam_id             = info["steamid"]
      u.steam_name           = info["personaname"]
      u.community_visibility = info["communityvisibilitystate"]
      u.profile_state        = info["profilestate"]
      u.last_logoff          = info["lastlogoff"]
      u.profile_url          = info["profileurl"]
      u.avatar               = info["avatar"]
      u.avatar_medium        = info["avatarmedium"]
      u.avatar_full          = info["avatarfull"]
      u.primary_clanid       = info["primaryclanid"]
      u.time_created         = info["timecreated"]
      u.person_state         = info["person_state"]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]


  def index
    @users = User.all
    User.random_method
  end

  def show
    @user = User.find(params[:id])
    @user_listings = @user.user_listings.paginate(:page => params[:page]).per_page(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.trade_url = params[:user][:trade_url]
    if @user.save
      flash[:success] = "You have successfully updated your Trading URL"
    else 
      flash[:error]   = "Something went wrong!"
    end
    sign_in @user
    redirect_to edit_user_path
  end

  helper_method :current_user
end

app/views/users/edit.html.erb
<div class="main-div">
    <h1>Settings</h1>
    <div class="row">
        <div class="col-xs-3 side-section">
            <ul class="list-group center">
                <li class="list-group-item active-side"><a href="#" class="trade-url-btn"><i class="fa fa-exchange"></i>  Update Trade URL</a></li>
                <li class="list-group-item"><a href="#" class="blocked-user-btn"><i class="fa fa-ban"></i> Blocked Users</a></li>
            </ul>
        </div>
        <div class="col-xs-9 main-section">
            <div class="trade-url-section">
                <h4>Update your trade URL:</h4>
                <div class="row">
                    <div class="input-group col-xs-12">
                    <%= form_for @user, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
                      <%= f.text_field :trade_url, {class: "form-control", placeholder: "Trade Url"} %>
                      <%= f.submit "Save", class: "btn btn-primary settings-btn" %>
                    <% end %>
                      <br/>
                      <p>Adding your Steam Trading URL will create a link on your profile and listings so that
                       users to send you trade requests through the Steam Client which will facllitate 
                       faster trading. 
                       </p>

                       <p>
                           To get your Trade Url, go to <a href="http://steamcommunity.com/my/tradeoffers/privacy">Trade Offer Privacy</a> settings and copy the URL into the form above. If you ever wish to change
                           your Trade Offer URL, you can go back to the same page and click "Create New URL."
                       </p>
                      <p>
                          <blockquote>You can share this your unique trade URL with other Steam users to allow them to send you a trade offer even if they aren't on your friends list. You can share this URL anywhere, including on third-party trading sites and Steam Community groups. -From Steam's trade offers page
                          </blockquote>
                      </p>
                      <p>
                          For more information, go to the official page <a href="https://support.steampowered.com/kb_article.php?ref=2178-QGJV-0708">here</a>.
                      </p>
                    </div>
                </div>
            </div>
            <div class="block-user-section">
              <div class="alert alert-danger">
                  You have blocked the users below. To unblock them, click "unblock."
              </div>
                <% if @user.other_users.blank? %>
                  <p> You have not blocked anyone.</p>
                <% else %>
                  <% @user.blocked_users.each do |blocked| %>
                     <%= blocked.steam_name %> 
                     <%= link_to "Unblock", unblock_user_path(:blocked_user_id => blocked, :user_id => @user), { :class=>"btn btn-primary" } %>
                  <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="main-div">
    <div class="row">
    <% if signed_in? %>
        <div class="col-xs-12">
            <%= render 'layouts/users_show' %>
        </div>
    
    <% else %>
         <div class="col-xs-12">
            <%= render 'layouts/users_show' %>
         </div>
     <% end %>
    </div>
</div>