config/routes.rb
DotaMarket::Application.routes.draw do


  concern :commentable do
    resources :comments
  end

  resources :users, concerns: :commentable do
    resources :messages do
      get "sent_messages", on: :collection
      get "conversation",  on: :collection
      member do 
        get 'marked_as_read'
      end
    end
   resources :user_listings
   resources :relationships, only: [:create, :update] #[:new, :create, :edit, :update, :destroy]
 end

  resources :user_listings, concerns: :commentable
 
  resources :items
  resources :sessions, only: [:create, :destroy]

  # SESSIONS ROUTES START #

  get  'auth/steam/callback' => 'sessions#create'
  post 'auth/steam/callback' => 'sessions#create'
  get  'auth/failure'         => redirect('/')
  delete 'signout'           => 'sessions#destroy'
  # match '/signout', to: 'sessions#destroy', via: :delete

  # SESSIONS ROUTES END #


  #resources :user_listings

  root to: 'static_pages#home'

  ### SHAMEFUL ROUTES BELOW ###

  get "search/new"
  get "search/create"
  get "search/show"
  match '/searched-items', to: 'search#show', via: :get
  match '/search', to: "user_listings#search", via: :get

  match "/faq", to: "static_pages#faq", via: :get
  match "/about", to: "static_pages#about", via: :get
  # match "/contact", to: "static_pages#contact"

  match '/reload', to: "user_listings#reload", via: :post

  match '/contact', to: "contact_messages#new", via: :get
  match '/signin', to: redirect('/auth/steam'), via: :get
  # match '/message_marked_as_read', to: "messages#marked_as_read"
  match '/block_user', to: "relationships#create", via: :get
  match '/unblock_user', to:  "relationships#update", via: :get
  match '/update', to: "users#update", via: :get


  ### SHAMEFUL ROUTES END ###
end

app/views/layouts/_comment.html.erb
      <div class="individual-comment row">
          <% if comment.user.avatar_medium.blank? || comment.user.avatar_medium.nil? %>
          <div class="avatar col-xs-1">
            <span><img src="http://media.steampowered.com/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_medium.jpg"></span>
          </div>
          <% else %>
            <div class="avatar col-xs-1">
              <%= link_to url_for(comment.user) do %>
                <span><img class="img-responsive" src="<%= comment.user.avatar_medium %>"></span>
              <% end %>
            </div>
          <% end %> 

          <div class="comment-header group col-xs-11">
            <div class="title clearfix">
                <span><%= comment.user.steam_name%> Posted <%= time_ago_in_words(comment.created_at) %> ago</span>
                <% if current_user == comment.user || @user_listing.user %>
                  <button type="button" class="btn btn-inverse pull-right" data-toggle="modal" data-target="#myModal"><%= link_to url_for([@user, comment]), class: "deleteButton" do %>
                      <i class="pull-right icon glyphicon glyphicon-trash"></i>
                  <% end %>
                  </button>
                <% end %>
            </div>
            <div class="menu comment-description">
              <%= comment.description %>
            </div>
          </div>
      </div>

app/views/layouts/_footer.html.erb
    <footer class="footer container">
        <small><a href="">DOTA Deals</a> by Piece of Cake. 
            Powered by <a href="http://steampowered.com ">Steam</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <li><%= link_to "FAQ", faq_path %></li>
            </ul>
        </nav>
    </footer>

app/views/layouts/_header.html.erb
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">         
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">DOTA DEALS</a>
                </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home", root_path %></li>
                        <% if signed_in? %>
                             <li><%= link_to "Profile", current_user %></li>
                             <li><%= link_to "New Listing", new_user_user_listing_path(current_user) %></li>
                             <li><%= link_to "Listings", user_user_listings_path(current_user) %></li>
                             <% if unread_messages(current_user) > 0 %>
                             <li><%= link_to "Messages (#{unread_messages(current_user)} unread)", user_messages_path(current_user) %></li>
                             <% else %>
                            <li><%= link_to "Messages", user_messages_path(current_user) %></li>
                             <% end %>
                             <li><%= link_to "Search", search_new_path %></li>
                             <li id="fat-menu" class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Account <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                    <li class="divider"></li>
                                    <li>
                                        <%= link_to "Sign out", signout_path, method: "delete" %>
                                    </li>
                                </ul>
                              </li>


                        <% else %>
                            <li><%= link_to "About", about_path %></li>
                            <li><%= link_to "FAQ", faq_path %></li>
                            <li><%= link_to "Sign in", "/auth/steam" %></li>
                        <% end %>
                    </ul>
            </div>
        </nav>

app/views/layouts/_listing.html.erb
  <div class="single-listing">
    <div class="title clearfix">
      <%= link_to url_for([listing.user, listing]) do %>
      <span class="messenger-name">  
          <% if listing.user.nil?  %>
            No name
          <% else %>
            <%= listing.user.steam_name %> 
          <% end %>
        at <%= time_ago_in_words(listing.created_at) %> ago wanted to trade ... </span>
      <% end %>
      <!-- BUTTONS -->
      <div class="btn-group pull-right">
        <div type="button" class="btn btn-inverse note-btn">
                <i class="pull-right icon fa fa-pencil"></i>
        </div>

        <% unless current_user == listing.user %>
          <div type="button" class="btn btn-inverse">
            <%= link_to new_user_message_path(current_user,  {recipient: listing.user}) do %>
             <i class="pull-right icon fa fa-comment-o"></i>
          <% end %>
          </div>
        <% end %>
        
        <% if current_user == listing.user %>
          <div type="button" class="btn btn-inverse" data-toggle="modal" data-target="#myModal"><%= link_to user_user_listing_path(listing.user, listing), class: "deleteButton" do %>
                <i class="pull-right icon glyphicon glyphicon-trash"></i>
            <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="menu">
      <div class="row clearfix">
        <div class="list-items-offered col-xs-5">
         <% listing.items_offered.each do |item| %>
            <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
              <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
            </li>
         <% end %>
        </div>

        <span class="col-xs-1 offer-icon glyphicon glyphicon-transfer"></span> 

        <div class="list-items-wanted col-xs-5">
         <% listing.items_wanted.each do |item| %>
            <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
            <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
            </li>
         <% end %>
        </div>
      </div>
    </div>

    <div class="note-section">
      <div class="title clearfix">
       <span>Notes</span>
        
      </div>

      <div class="note-body menu">
        <% if listing.comments.first.nil? %>
        <span>No comment </span>
        <% else %> 
            <%= listing.comments.first.description %>
        <% end %>
      </div>
    </div>
  </div>

app/views/layouts/_message_button.html.erb
<div class="btn-group">
  <div type="button" class="btn btn-default"><%= link_to url_for([@user, message]), {:method => :delete} do %>
                            <i class="pull-right icon glyphicon glyphicon-trash"></i>
                        <% end %></div>
  <div type="button" class="btn btn-default"><%= link_to new_user_message_path({recipient: message.messenger}) do %>
                            <i class="pull-right icon fa fa-reply"></i>
                        <% end %></div>
  <div type="button" class="btn btn-default"><%= link_to user_message_path({:id => message.id}) do %>
                            <i class="pull-right icon fa fa-comments"></i>
                        <% end %></div>
</div>

app/views/layouts/_messages_side_bar.html.erb
<div class="messages-sidebar sidebar">
    <div class="sidebar-menu clearfix">
        <ul class="text-center">
            <li><%= link_to "Sent Messages", sent_messages_user_messages_path %><i class="fa fa-check-square"></i></li>
        </ul>
    </div>
</div>

app/views/layouts/_modal.html.erb
    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Confirm</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="dist/html5shiv.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
    <div class="sidebar-avatar center">
            <img class="img-thumbnail" src="<%= current_user.avatar_medium %>">
            <p class="user-name"><%= current_user.steam_name %></p>
    </div>

    <div class="sidebar-menu clearfix">
        <ul>
            <li><span><i class="fa fa-search"></i></i></span><%= link_to "Search" , search_new_path %></li>
            <li><span><i class="fa fa-pencil-square-o"></i></span><%= link_to "New Listing", new_user_user_listing_path(current_user) %></li>
            <li><span><i class="fa fa-th-list"></i></span><%= link_to "Listings", user_user_listings_path(current_user) %></li>
            <li><span><i class="fa fa-briefcase"></i></span><%= link_to "Backpack", user_path(current_user) %></li>
            <li><span><i class="fa fa-envelope"></i></span><%= link_to "Messages", user_messages_path(current_user) %></li>
        </ul>
    </div>
</div>

app/views/layouts/_user_listings.html.erb
<div class="row menu">
  <div class="title">
        <span><%= @user_listing.user.steam_name %> at <%= time_ago_in_words(@user_listing.created_at) %> ago wanted to trade ...</span>
  </div>

    <div class="col-xs-6 items-offered">
      <h3>Items Offered:</h3>
      <% @user_listing.items_offered.each do |item| %>
             <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
                  <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
                </li>
      <% end %>
    </div>
    <div class="col-xs-6 items-wanted">
      <h3>Items Wanted:</h3>
      <% @user_listing.items_wanted.each do |item| %>
             <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
                  <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
              </li>
      <% end %>
    </div>
</div>

    <% if signed_in? %>
      <div class="commenting-area row">
        <div class="title">
                    <span>New Comment</span>
        </div>
        <%= form_for([@user_listing, Comment.new], {class: "forms-val"}) do |f| %>
                <%= f.text_area :description, placeholder: "Type comments here" %>
                <%= hidden_field_tag(:listing_id, @user_listing.id) %>
                <%= hidden_field_tag(:user_id, current_user.id) %>
                <%= f.submit "Add Comment", class: "btn btn-primary" %>
        <% end %>
    <% end %>
      <%= render partial: "layouts/comment", collection: @comments %>
   </div>
 </div>

app/views/layouts/_users_show.html.erb
<div class="user-stats clearfix">
    <div class="user-stats-outside">
        <div class="user-stats-main">
            <div class="user-img col-xs-2">
                <img class="img-circle img-responsive" src="<%= @user.avatar_full %>">
            </div>
    
             <div class="user-stats-sub col-xs-6">
                 <p class="steam-name"><%= @user.steam_name %></p>
                 <div class="row user-stats-options center">
                  <% unless current_user == @user %>
                     <div class="col-xs-3">
                        <%= link_to new_user_message_path(current_user,  {recipient: @user}) do %>
                          <i class="fa fa-comment-o"></i>
                          <p>Message User</p>
                        <% end %>
                     </div>

                      <div class="col-xs-3">
                       <%= link_to user_relationships_path(current_user, {blocked_user: @user.id}), :data => {:type => "block", :toggle => "modal", :target => "#myModal"}, class: "blockButton" do %>
                          <i class="fa fa-ban"></i>
                          <p>Block User</p>
                        <% end %>
                     </div>
                  <% end %>

                  <% unless current_user.trade_url.blank? %>
                     <div class="col-xs-3">
                      <%= link_to current_user.trade_url do %>
                        <i class="fa fa-paper-plane-o"></i>
                         <p>Trade Request</p>
                      <% end %>
                     </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="backpack-section menu main-backpack-section">
    <div class="title">
        <ul class="nav nav-tabs" role="tablist">
          <li class="profile-links active user-items-btn"><a href="#">Backpack <span class="badge"><%= @user.items.count %></span></a></li>
          <li class="profile-links user-listings-btn"><a href="#">User Listings <span class="badge"><%= @user.user_listings.count %></span></a></li>
        </ul>
    </div>

    <div class="user-backpack backpack user-backpack-items">
        <ul class="clearfix">
        <% @user.items.each do |item| %>
             <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
                                <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
             </li>
        <% end %>
        </ul>
    </div>

    <div class="user-backpack backpack user-backpack-listings">
        <% @user.user_listings.each do |listings| %>
        <div class="single-listing">
          <div class="title clearfix">
            <%= link_to url_for([@user, listings]) do %>
              <span class="messenger-name"><%= listings.user.steam_name %> at <%= time_ago_in_words(listings.created_at) %> ago wanted to trade ... </span>
            <% end %>
            <div class="btn-group pull-right">  

            <div type="button" class="btn btn-inverse note-btn">
                                      <i class="pull-right icon fa fa-comment-o"></i>
                                  </div>
            <div type="button" class="btn btn-inverse"><%= link_to url_for([@user, listings]), {:method => :delete} do %>
                  <i class="pull-right icon glyphicon glyphicon-trash"></i>
              <% end %>
            </div>
          </div>
        </div>
          <div class="menu">
            <div class="row clearfix">
              <div class="list-items-offered col-xs-5">
               <% listings.items_offered.each do |item| %>
                  <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
                    <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
                  </li>
               <% end %>
              </div>

                <span class="col-xs-1 offer-icon glyphicon glyphicon-transfer"></span> 

                <div class="list-items-wanted col-xs-5">
                 <% listings.items_wanted.each do |item| %>
                    <li class="item-li thumbnail <%= item.rarity %>" data-toggle="tooltip" data-placement="bottom" title="<%= item.rarity.capitalize unless item.rarity.nil? %> <%= item.name %>" data-id="<%= item.id %>" data-name="<%= item.name %>" data-rarity="<%= item.rarity %>" data-defindex="<%= item.defindex %>">
                    <a href="/items/<%= item.id %>"><img src="<%= item.image_url %>"></a> 
                  </li>
                 <% end %>
                </div>
              </div>
          </div>

          <div class="note-section">
            <div class="title clearfix">
              <span>Notes</span>
              
            </div>

            <div class="note-body menu">
              <% if listings.comments.first.nil? %>
                  <span>No comment </span>
              <% else %> 
                  <%= listings.comments.first.description %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>

         <div class="pagination">
            <%= will_paginate @user_listings, renderer: BootstrapPagination::Rails, class: "pagination-lg" %>
        </div>
    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%=  full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>

    </head>
    <body>
    
          <%= render 'layouts/header' %>
          
     <div class="container">
        <%= yield %>
     </div> 

  
    <% flash.each do |type, message| %>
      <div class="alert flash alert-<%= type %> alert-dismissable goodbye">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><%= message %></strong>     
      </div>
    <% end %>

    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        Are you sure you want to delete?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a class="btn btn-primary" data-method="delete">Save changes</a>
      </div>
    </div>
  </div>
</div>

    <%= render 'layouts/footer' %>
</body>
    <%= javascript_include_tag "market" %>

</html>